recorder: !include components/recorder.yaml

homeassistant:
  name: JARVIS
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 334
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customizations
  customize_glob: !include customize_glob.yaml

customizer:
  custom_ui: local

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-custom-alarm.html
    - /local/custom_ui/state-card-custom-fanspeed.html
    - /local/custom_ui/momentjs.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-custom-alarm.html
    - /local/custom_ui/state-card-custom-fanspeed.html
